# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Analysed'),
            preserve_default=False,
        ),
    ]
